spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
      show_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: jdbc:mysql://localhost:3306/biller
    username: root
    password: logx73
    driverClassName: com.mysql.cj.jdbc.Driver






