openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v1.0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: metadata-controller
    description: APIs For Metadata
  - name: farmer-controller
    description: APIs For Farmer
paths:
  /saveMetadata:
    post:
      tags:
        - metadata-controller
      operationId: saveBill
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetadataDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataDto'
  /saveFarmer:
    post:
      tags:
        - farmer-controller
      operationId: insertFarmer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FarmerDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FarmerDto'
  /getFarmer/{searchParam}:
    get:
      tags:
        - farmer-controller
      operationId: getFarmers
      parameters:
        - name: searchParam
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FarmerDto'
components:
  schemas:
    GoodsDto:
      type: object
      properties:
        price:
          type: number
          format: float
        weight:
          type: number
          format: double
        rate:
          type: number
          format: double
        amount:
          type: number
        advanceAmount:
          type: number
        checkNumber:
          type: string
        purchased:
          type: string
          format: date
    MetadataDto:
      type: object
      properties:
        farmerId:
          type: integer
          format: int64
        lastUpdated:
          type: string
          format: date
        status:
          type: string
        goodsList:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/GoodsDto'
    FarmerDto:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        mobile:
          type: string
        email:
          type: string
        address:
          type: string
