openapi: 3.0.3
info:
  title: Swagger Biller
  version: 1.0.11
servers:
  - url: /v3
tags:
  - name: shetkari_record
    description: Everything about shetkari
  - name: metadata
    description: Billers Metadata
  - name: goods_record
    description: Everything about goods
paths:
  /saveGoods:
    post:
      tags:
        - goods_record
      summary: Saves Goods Record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoodRecord'
          application/xml:
            schema:
              $ref: '#/components/schemas/GoodRecord'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GoodRecord'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodRecord'
            application/xml:
              schema:
                $ref: '#/components/schemas/GoodRecord'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
  /metadata:
    get:
      tags:
        - metadata
      summary: Get Metadata Record By Id
      parameters:
        - name: pattiId
          in: query
          description: ID to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetaData'
            application/xml:
              schema:
                $ref: '#/components/schemas/MetaData'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
    post:
      tags:
        - metadata
      summary: Saves metadata Record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetaData'
          application/xml:
            schema:
              $ref: '#/components/schemas/MetaData'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MetaData'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetaData'
            application/xml:
              schema:
                $ref: '#/components/schemas/MetaData'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
components:
  schemas:
    GoodRecord:
      type: object
      properties:
        patti_id:
          type: integer
          format: int64
          example: 10
        date_of_purchase:
          type: string
          format: date
          example: 17-04-2022
        weight:
          type: number
          format: double
        rate:
          type: number
          format: float
        amount:
          type: number
          format: double
        adv_amount:
          type: number
          format: double
        check_no:
          type: integer
          format: int64
        mandatory_deductions:
          type: integer
          format: int32
    MetaData:
      type: object
      properties:
        patti_number:
          type: integer
          format: int64
        shatkari_name:
          type: string
        goodsRecord:
          type: array
          items:
            $ref: '#/components/schemas/GoodRecord'
        status:
          type: boolean

